import type { Topic, Word, Sentence } from './types';

// ─── Topics ───────────────────────────────────────────────────────────────────

export const TOPICS: Topic[] = [
  {
    id: 'travel',
    name: 'Du lịch',
    description: 'Từ vựng về du lịch, khám phá và phiêu lưu',
    emoji: '✈️',
    wordCount: 10,
    type: 'system',
  },
  {
    id: 'work',
    name: 'Công việc',
    description: 'Từ vựng về môi trường làm việc và sự nghiệp',
    emoji: '💼',
    wordCount: 10,
    type: 'system',
  },
  {
    id: 'family',
    name: 'Gia đình',
    description: 'Từ vựng về gia đình, các mối quan hệ và truyền thống',
    emoji: '👨‍👩‍👧‍👦',
    wordCount: 10,
    type: 'system',
  },
  {
    id: 'technology',
    name: 'Công nghệ',
    description: 'Từ vựng về công nghệ, phần mềm và kỹ thuật số',
    emoji: '💻',
    wordCount: 10,
    type: 'system',
  },
  {
    id: 'toeic',
    name: 'TOEIC',
    description: 'Từ vựng thương mại và kinh doanh cho bài thi TOEIC',
    emoji: '📊',
    wordCount: 10,
    type: 'system',
  },
];

// ─── Words ────────────────────────────────────────────────────────────────────

export const WORDS: Record<string, Word[]> = {
  travel: [
    {
      id: 'travel-airport',
      topicId: 'travel',
      english: 'airport',
      vietnamese: ['sân bay', 'phi trường'],
      ipa: '/ˈɛərpɔːrt/',
      example: 'We arrived at the airport two hours before departure.',
      exampleVi: 'Chúng tôi đến sân bay hai giờ trước khi khởi hành.',
    },
    {
      id: 'travel-luggage',
      topicId: 'travel',
      english: 'luggage',
      vietnamese: ['hành lý', 'đồ đạc', 'va li'],
      ipa: '/ˈlʌɡɪdʒ/',
      example: 'Please make sure your luggage does not exceed 23 kilograms.',
      exampleVi: 'Vui lòng đảm bảo hành lý của bạn không vượt quá 23 kg.',
    },
    {
      id: 'travel-passport',
      topicId: 'travel',
      english: 'passport',
      vietnamese: ['hộ chiếu', 'giấy thông hành'],
      ipa: '/ˈpɑːspɔːrt/',
      example: "Don't forget to bring your passport when you travel abroad.",
      exampleVi: 'Đừng quên mang hộ chiếu khi bạn đi du lịch nước ngoài.',
    },
    {
      id: 'travel-ticket',
      topicId: 'travel',
      english: 'ticket',
      vietnamese: ['vé', 'vé máy bay', 'phiếu'],
      ipa: '/ˈtɪkɪt/',
      example: 'She booked a round-trip ticket to Paris last week.',
      exampleVi: 'Cô ấy đặt vé khứ hồi đến Paris tuần trước.',
    },
    {
      id: 'travel-hotel',
      topicId: 'travel',
      english: 'hotel',
      vietnamese: ['khách sạn', 'nhà nghỉ'],
      ipa: '/hoʊˈtɛl/',
      example: 'The hotel has a stunning view of the ocean.',
      exampleVi: 'Khách sạn có tầm nhìn tuyệt đẹp ra đại dương.',
    },
    {
      id: 'travel-tourist',
      topicId: 'travel',
      english: 'tourist',
      vietnamese: ['khách du lịch', 'du khách'],
      ipa: '/ˈtʊərɪst/',
      example: 'Thousands of tourists visit the temple every year.',
      exampleVi: 'Hàng nghìn du khách đến thăm ngôi đền mỗi năm.',
    },
    {
      id: 'travel-destination',
      topicId: 'travel',
      english: 'destination',
      vietnamese: ['điểm đến', 'nơi đến', 'đích đến'],
      ipa: '/ˌdɛstɪˈneɪʃən/',
      example: 'Bali is a popular holiday destination for travelers worldwide.',
      exampleVi: 'Bali là điểm đến nghỉ lễ phổ biến với du khách toàn cầu.',
    },
    {
      id: 'travel-journey',
      topicId: 'travel',
      english: 'journey',
      vietnamese: ['hành trình', 'cuộc hành trình', 'chuyến đi'],
      ipa: '/ˈdʒɜːrni/',
      example: 'The journey from Hanoi to Ho Chi Minh City takes two hours by plane.',
      exampleVi: 'Hành trình từ Hà Nội đến TP. HCM mất hai giờ bằng máy bay.',
    },
    {
      id: 'travel-reservation',
      topicId: 'travel',
      english: 'reservation',
      vietnamese: ['đặt chỗ', 'đặt trước', 'sự đặt phòng'],
      ipa: '/ˌrɛzərˈveɪʃən/',
      example: 'I made a reservation at the restaurant for seven people.',
      exampleVi: 'Tôi đặt chỗ trước tại nhà hàng cho bảy người.',
    },
    {
      id: 'travel-departure',
      topicId: 'travel',
      english: 'departure',
      vietnamese: ['sự khởi hành', 'chuyến đi', 'lúc khởi hành'],
      ipa: '/dɪˈpɑːrtʃər/',
      example: 'The departure gate for our flight is located at Terminal 2.',
      exampleVi: 'Cổng khởi hành của chuyến bay chúng tôi nằm ở Nhà ga 2.',
    },
  ],

  work: [
    {
      id: 'work-meeting',
      topicId: 'work',
      english: 'meeting',
      vietnamese: ['cuộc họp', 'cuộc gặp mặt', 'buổi họp'],
      ipa: '/ˈmiːtɪŋ/',
      example: 'The team has a weekly meeting every Monday morning.',
      exampleVi: 'Nhóm có cuộc họp hàng tuần vào mỗi sáng thứ Hai.',
    },
    {
      id: 'work-deadline',
      topicId: 'work',
      english: 'deadline',
      vietnamese: ['hạn chót', 'thời hạn', 'deadline'],
      ipa: '/ˈdɛdlaɪn/',
      example: 'We must submit the report before the deadline on Friday.',
      exampleVi: 'Chúng ta phải nộp báo cáo trước hạn chót vào thứ Sáu.',
    },
    {
      id: 'work-colleague',
      topicId: 'work',
      english: 'colleague',
      vietnamese: ['đồng nghiệp', 'người cùng làm việc'],
      ipa: '/ˈkɒliːɡ/',
      example: 'My colleague helped me finish the project on time.',
      exampleVi: 'Đồng nghiệp của tôi đã giúp tôi hoàn thành dự án đúng hạn.',
    },
    {
      id: 'work-project',
      topicId: 'work',
      english: 'project',
      vietnamese: ['dự án', 'công trình', 'đề án'],
      ipa: '/ˈprɒdʒɛkt/',
      example: 'The new project will launch in the third quarter of this year.',
      exampleVi: 'Dự án mới sẽ ra mắt vào quý ba năm nay.',
    },
    {
      id: 'work-salary',
      topicId: 'work',
      english: 'salary',
      vietnamese: ['lương', 'mức lương', 'tiền lương'],
      ipa: '/ˈsæləri/',
      example: 'She negotiated a higher salary during her job interview.',
      exampleVi: 'Cô ấy thương lượng mức lương cao hơn trong buổi phỏng vấn.',
    },
    {
      id: 'work-promotion',
      topicId: 'work',
      english: 'promotion',
      vietnamese: ['sự thăng chức', 'thăng tiến', 'khuyến mãi'],
      ipa: '/prəˈmoʊʃən/',
      example: 'He received a promotion after three years of hard work.',
      exampleVi: 'Anh ấy được thăng chức sau ba năm làm việc chăm chỉ.',
    },
    {
      id: 'work-interview',
      topicId: 'work',
      english: 'interview',
      vietnamese: ['phỏng vấn', 'buổi phỏng vấn'],
      ipa: '/ˈɪntərvjuː/',
      example: 'She prepared carefully for the job interview at the tech company.',
      exampleVi: 'Cô ấy chuẩn bị kỹ lưỡng cho buổi phỏng vấn tại công ty công nghệ.',
    },
    {
      id: 'work-contract',
      topicId: 'work',
      english: 'contract',
      vietnamese: ['hợp đồng', 'bản hợp đồng', 'hợp đồng lao động'],
      ipa: '/ˈkɒntrækt/',
      example: 'Both parties signed the contract at the end of the meeting.',
      exampleVi: 'Cả hai bên đã ký hợp đồng vào cuối cuộc họp.',
    },
    {
      id: 'work-teamwork',
      topicId: 'work',
      english: 'teamwork',
      vietnamese: ['làm việc nhóm', 'tinh thần đồng đội', 'hợp tác nhóm'],
      ipa: '/ˈtiːmwɜːrk/',
      example: 'Good teamwork is essential to achieving company goals.',
      exampleVi: 'Làm việc nhóm tốt là điều cần thiết để đạt được mục tiêu công ty.',
    },
    {
      id: 'work-productivity',
      topicId: 'work',
      english: 'productivity',
      vietnamese: ['năng suất', 'hiệu suất làm việc', 'năng suất lao động'],
      ipa: '/ˌproʊdʌkˈtɪvɪti/',
      example: 'Remote work has greatly increased her productivity.',
      exampleVi: 'Làm việc từ xa đã tăng đáng kể năng suất của cô ấy.',
    },
  ],

  family: [
    {
      id: 'family-parents',
      topicId: 'family',
      english: 'parents',
      vietnamese: ['cha mẹ', 'bố mẹ', 'ba mẹ'],
      ipa: '/ˈpɛərənts/',
      example: 'Her parents always supported her dreams and ambitions.',
      exampleVi: 'Cha mẹ cô ấy luôn ủng hộ những ước mơ và khát vọng của cô.',
    },
    {
      id: 'family-sibling',
      topicId: 'family',
      english: 'sibling',
      vietnamese: ['anh chị em', 'anh em ruột', 'chị em ruột'],
      ipa: '/ˈsɪblɪŋ/',
      example: 'He has two siblings: an older sister and a younger brother.',
      exampleVi: 'Anh ấy có hai anh chị em: một chị gái và một em trai.',
    },
    {
      id: 'family-relative',
      topicId: 'family',
      english: 'relative',
      vietnamese: ['họ hàng', 'người thân', 'bà con'],
      ipa: '/ˈrɛlətɪv/',
      example: 'Many relatives gathered for the family reunion last summer.',
      exampleVi: 'Nhiều người thân đã tụ họp cho buổi hội ngộ gia đình hè trước.',
    },
    {
      id: 'family-marriage',
      topicId: 'family',
      english: 'marriage',
      vietnamese: ['hôn nhân', 'cuộc hôn nhân', 'việc kết hôn'],
      ipa: '/ˈmærɪdʒ/',
      example: 'Their marriage has been happy and strong for over twenty years.',
      exampleVi: 'Cuộc hôn nhân của họ hạnh phúc và bền vững hơn hai mươi năm.',
    },
    {
      id: 'family-household',
      topicId: 'family',
      english: 'household',
      vietnamese: ['hộ gia đình', 'gia đình', 'hộ'],
      ipa: '/ˈhaʊshoʊld/',
      example: 'The entire household shares the chores equally.',
      exampleVi: 'Cả hộ gia đình cùng chia sẻ công việc nhà một cách bình đẳng.',
    },
    {
      id: 'family-generation',
      topicId: 'family',
      english: 'generation',
      vietnamese: ['thế hệ', 'thế hệ con người', 'đời'],
      ipa: '/ˌdʒɛnəˈreɪʃən/',
      example: 'This tradition has been passed down through many generations.',
      exampleVi: 'Truyền thống này đã được truyền qua nhiều thế hệ.',
    },
    {
      id: 'family-heritage',
      topicId: 'family',
      english: 'heritage',
      vietnamese: ['di sản', 'gia sản', 'di sản văn hóa'],
      ipa: '/ˈhɛrɪtɪdʒ/',
      example: 'She is proud of her Vietnamese cultural heritage.',
      exampleVi: 'Cô ấy tự hào về di sản văn hóa Việt Nam của mình.',
    },
    {
      id: 'family-tradition',
      topicId: 'family',
      english: 'tradition',
      vietnamese: ['truyền thống', 'phong tục', 'tập tục'],
      ipa: '/trəˈdɪʃən/',
      example: 'It is a family tradition to have dinner together every Sunday.',
      exampleVi: 'Đó là truyền thống gia đình là ăn tối cùng nhau mỗi Chủ nhật.',
    },
    {
      id: 'family-caregiver',
      topicId: 'family',
      english: 'caregiver',
      vietnamese: ['người chăm sóc', 'người trông nom', 'người nuôi dưỡng'],
      ipa: '/ˈkɛrɡɪvər/',
      example: 'She became the primary caregiver for her elderly mother.',
      exampleVi: 'Cô ấy trở thành người chăm sóc chính cho mẹ già của mình.',
    },
    {
      id: 'family-reunion',
      topicId: 'family',
      english: 'reunion',
      vietnamese: ['buổi đoàn tụ', 'sự đoàn tụ', 'hội ngộ'],
      ipa: '/riːˈjuːnjən/',
      example: 'The family reunion during Tet is always a joyful occasion.',
      exampleVi: 'Buổi đoàn tụ gia đình trong dịp Tết luôn là dịp vui vẻ.',
    },
  ],

  technology: [
    {
      id: 'technology-software',
      topicId: 'technology',
      english: 'software',
      vietnamese: ['phần mềm', 'chương trình máy tính'],
      ipa: '/ˈsɒftwɛər/',
      example: 'The company released a major software update last month.',
      exampleVi: 'Công ty đã phát hành bản cập nhật phần mềm lớn tháng trước.',
    },
    {
      id: 'technology-hardware',
      topicId: 'technology',
      english: 'hardware',
      vietnamese: ['phần cứng', 'thiết bị phần cứng'],
      ipa: '/ˈhɑːrdwɛər/',
      example: 'The hardware upgrade significantly improved the computer speed.',
      exampleVi: 'Việc nâng cấp phần cứng đã cải thiện đáng kể tốc độ máy tính.',
    },
    {
      id: 'technology-network',
      topicId: 'technology',
      english: 'network',
      vietnamese: ['mạng', 'mạng lưới', 'hệ thống mạng'],
      ipa: '/ˈnɛtwɜːrk/',
      example: 'The office network was down for two hours due to maintenance.',
      exampleVi: 'Mạng văn phòng bị ngắt trong hai giờ do bảo trì.',
    },
    {
      id: 'technology-database',
      topicId: 'technology',
      english: 'database',
      vietnamese: ['cơ sở dữ liệu', 'cơ sở dữ liệu số', 'database'],
      ipa: '/ˈdeɪtəbeɪs/',
      example: 'All customer information is stored securely in the database.',
      exampleVi: 'Tất cả thông tin khách hàng được lưu trữ an toàn trong cơ sở dữ liệu.',
    },
    {
      id: 'technology-algorithm',
      topicId: 'technology',
      english: 'algorithm',
      vietnamese: ['thuật toán', 'giải thuật'],
      ipa: '/ˈælɡərɪðəm/',
      example: 'The search engine uses a complex algorithm to rank results.',
      exampleVi: 'Công cụ tìm kiếm sử dụng thuật toán phức tạp để xếp hạng kết quả.',
    },
    {
      id: 'technology-cybersecurity',
      topicId: 'technology',
      english: 'cybersecurity',
      vietnamese: ['an ninh mạng', 'bảo mật mạng', 'an toàn thông tin'],
      ipa: '/ˌsaɪbərsɪˈkjʊərɪti/',
      example: 'Cybersecurity threats are becoming more sophisticated every year.',
      exampleVi: 'Các mối đe dọa an ninh mạng ngày càng tinh vi hơn mỗi năm.',
    },
    {
      id: 'technology-artificial',
      topicId: 'technology',
      english: 'artificial',
      vietnamese: ['nhân tạo', 'giả tạo', 'mô phỏng'],
      ipa: '/ˌɑːrtɪˈfɪʃəl/',
      example: 'Artificial intelligence is transforming many industries worldwide.',
      exampleVi: 'Trí tuệ nhân tạo đang biến đổi nhiều ngành công nghiệp trên toàn cầu.',
    },
    {
      id: 'technology-innovation',
      topicId: 'technology',
      english: 'innovation',
      vietnamese: ['đổi mới', 'sự sáng tạo', 'cải tiến'],
      ipa: '/ˌɪnəˈveɪʃən/',
      example: 'Continuous innovation keeps the company ahead of its competitors.',
      exampleVi: 'Đổi mới liên tục giúp công ty đi trước các đối thủ cạnh tranh.',
    },
    {
      id: 'technology-smartphone',
      topicId: 'technology',
      english: 'smartphone',
      vietnamese: ['điện thoại thông minh', 'smartphone'],
      ipa: '/ˈsmɑːrtfoʊn/',
      example: 'Modern smartphones can perform tasks that once required a desktop computer.',
      exampleVi: 'Điện thoại thông minh hiện đại có thể thực hiện các tác vụ từng cần máy tính để bàn.',
    },
    {
      id: 'technology-bandwidth',
      topicId: 'technology',
      english: 'bandwidth',
      vietnamese: ['băng thông', 'dải thông', 'độ rộng băng tần'],
      ipa: '/ˈbændwɪdθ/',
      example: 'Streaming 4K video requires a lot of internet bandwidth.',
      exampleVi: 'Xem video 4K trực tuyến đòi hỏi nhiều băng thông internet.',
    },
  ],

  toeic: [
    {
      id: 'toeic-inventory',
      topicId: 'toeic',
      english: 'inventory',
      vietnamese: ['hàng tồn kho', 'kiểm kê', 'danh mục hàng hóa'],
      ipa: '/ˈɪnvəntɔːri/',
      example: 'The warehouse manager conducted a full inventory check at year end.',
      exampleVi: 'Quản lý kho đã tiến hành kiểm kê toàn bộ hàng hóa vào cuối năm.',
    },
    {
      id: 'toeic-merchandise',
      topicId: 'toeic',
      english: 'merchandise',
      vietnamese: ['hàng hóa', 'hàng mua bán', 'sản phẩm thương mại'],
      ipa: '/ˈmɜːrtʃəndaɪs/',
      example: 'The store displayed its latest merchandise in the front window.',
      exampleVi: 'Cửa hàng trưng bày hàng hóa mới nhất ở cửa sổ phía trước.',
    },
    {
      id: 'toeic-revenue',
      topicId: 'toeic',
      english: 'revenue',
      vietnamese: ['doanh thu', 'thu nhập', 'nguồn thu'],
      ipa: '/ˈrɛvənjuː/',
      example: 'The company reported record revenue in the last financial quarter.',
      exampleVi: 'Công ty ghi nhận doanh thu kỷ lục trong quý tài chính vừa qua.',
    },
    {
      id: 'toeic-expenditure',
      topicId: 'toeic',
      english: 'expenditure',
      vietnamese: ['chi tiêu', 'chi phí', 'khoản chi'],
      ipa: '/ɪkˈspɛndɪtʃər/',
      example: 'The board approved a new plan to reduce annual expenditure.',
      exampleVi: 'Hội đồng quản trị phê duyệt kế hoạch mới để giảm chi tiêu hàng năm.',
    },
    {
      id: 'toeic-negotiate',
      topicId: 'toeic',
      english: 'negotiate',
      vietnamese: ['đàm phán', 'thương lượng', 'đàm phán hợp đồng'],
      ipa: '/nɪˈɡoʊʃieɪt/',
      example: 'The two companies will negotiate the terms of the partnership next week.',
      exampleVi: 'Hai công ty sẽ đàm phán các điều khoản hợp tác vào tuần tới.',
    },
    {
      id: 'toeic-correspondence',
      topicId: 'toeic',
      english: 'correspondence',
      vietnamese: ['thư từ', 'sự trao đổi thư tín', 'liên lạc văn bản'],
      ipa: '/ˌkɒrɪˈspɒndəns/',
      example: 'All business correspondence must be answered within two working days.',
      exampleVi: 'Tất cả thư từ kinh doanh phải được trả lời trong vòng hai ngày làm việc.',
    },
    {
      id: 'toeic-consultant',
      topicId: 'toeic',
      english: 'consultant',
      vietnamese: ['chuyên gia tư vấn', 'tư vấn viên', 'cố vấn'],
      ipa: '/kənˈsʌltənt/',
      example: 'They hired an external consultant to improve their marketing strategy.',
      exampleVi: 'Họ thuê một chuyên gia tư vấn bên ngoài để cải thiện chiến lược marketing.',
    },
    {
      id: 'toeic-headquarters',
      topicId: 'toeic',
      english: 'headquarters',
      vietnamese: ['trụ sở chính', 'văn phòng trung tâm', 'tổng hành dinh'],
      ipa: '/ˈhɛdkwɔːrtərz/',
      example: 'The company moved its headquarters to Singapore last year.',
      exampleVi: 'Công ty đã chuyển trụ sở chính sang Singapore năm ngoái.',
    },
    {
      id: 'toeic-subsidiary',
      topicId: 'toeic',
      english: 'subsidiary',
      vietnamese: ['công ty con', 'chi nhánh', 'công ty phụ thuộc'],
      ipa: '/səbˈsɪdiɛri/',
      example: 'The subsidiary operates independently but reports to the parent company.',
      exampleVi: 'Công ty con hoạt động độc lập nhưng báo cáo lên công ty mẹ.',
    },
    {
      id: 'toeic-fluctuate',
      topicId: 'toeic',
      english: 'fluctuate',
      vietnamese: ['dao động', 'biến động', 'thay đổi thất thường'],
      ipa: '/ˈflʌktʃueɪt/',
      example: 'Oil prices tend to fluctuate based on global supply and demand.',
      exampleVi: 'Giá dầu có xu hướng dao động dựa trên cung cầu toàn cầu.',
    },
  ],
};

// ─── Sentences (dùng cho game sắp xếp câu) ───────────────────────────────────

export const SENTENCES: Record<string, Sentence[]> = {
  travel: [
    {
      english: 'I need to check in my luggage at the airport.',
      vietnamese: 'Tôi cần làm thủ tục gửi hành lý tại sân bay.',
      words: ['I', 'need', 'to', 'check', 'in', 'my', 'luggage', 'at', 'the', 'airport.'],
    },
    {
      english: 'She showed her passport to the immigration officer.',
      vietnamese: 'Cô ấy xuất trình hộ chiếu cho nhân viên hải quan.',
      words: ['She', 'showed', 'her', 'passport', 'to', 'the', 'immigration', 'officer.'],
    },
    {
      english: 'The tourist bought a ticket for the museum tour.',
      vietnamese: 'Du khách mua vé tham quan bảo tàng.',
      words: ['The', 'tourist', 'bought', 'a', 'ticket', 'for', 'the', 'museum', 'tour.'],
    },
    {
      english: 'Our destination is a beautiful coastal city.',
      vietnamese: 'Điểm đến của chúng tôi là một thành phố ven biển xinh đẹp.',
      words: ['Our', 'destination', 'is', 'a', 'beautiful', 'coastal', 'city.'],
    },
    {
      english: 'We made a hotel reservation for three nights.',
      vietnamese: 'Chúng tôi đặt phòng khách sạn trong ba đêm.',
      words: ['We', 'made', 'a', 'hotel', 'reservation', 'for', 'three', 'nights.'],
    },
    {
      english: 'The departure was delayed by an hour due to bad weather.',
      vietnamese: 'Chuyến khởi hành bị trễ một giờ do thời tiết xấu.',
      words: ['The', 'departure', 'was', 'delayed', 'by', 'an', 'hour', 'due', 'to', 'bad', 'weather.'],
    },
  ],

  work: [
    {
      english: 'The team finished the project before the deadline.',
      vietnamese: 'Nhóm đã hoàn thành dự án trước hạn chót.',
      words: ['The', 'team', 'finished', 'the', 'project', 'before', 'the', 'deadline.'],
    },
    {
      english: 'Good teamwork leads to higher productivity at work.',
      vietnamese: 'Làm việc nhóm tốt dẫn đến năng suất cao hơn ở nơi làm việc.',
      words: ['Good', 'teamwork', 'leads', 'to', 'higher', 'productivity', 'at', 'work.'],
    },
    {
      english: 'She got a promotion after a successful interview.',
      vietnamese: 'Cô ấy được thăng chức sau một buổi phỏng vấn thành công.',
      words: ['She', 'got', 'a', 'promotion', 'after', 'a', 'successful', 'interview.'],
    },
    {
      english: 'My colleague and I signed the contract together.',
      vietnamese: 'Đồng nghiệp và tôi đã cùng ký hợp đồng.',
      words: ['My', 'colleague', 'and', 'I', 'signed', 'the', 'contract', 'together.'],
    },
    {
      english: 'The salary increase was announced at the weekly meeting.',
      vietnamese: 'Thông báo tăng lương được đưa ra tại cuộc họp hàng tuần.',
      words: ['The', 'salary', 'increase', 'was', 'announced', 'at', 'the', 'weekly', 'meeting.'],
    },
    {
      english: 'He worked overtime to meet the project deadline.',
      vietnamese: 'Anh ấy làm thêm giờ để đáp ứng hạn chót của dự án.',
      words: ['He', 'worked', 'overtime', 'to', 'meet', 'the', 'project', 'deadline.'],
    },
  ],

  family: [
    {
      english: 'My parents always support my decisions in life.',
      vietnamese: 'Cha mẹ tôi luôn ủng hộ các quyết định của tôi trong cuộc sống.',
      words: ['My', 'parents', 'always', 'support', 'my', 'decisions', 'in', 'life.'],
    },
    {
      english: 'The family reunion brought everyone together with joy.',
      vietnamese: 'Buổi đoàn tụ gia đình mang mọi người lại với nhau trong niềm vui.',
      words: ['The', 'family', 'reunion', 'brought', 'everyone', 'together', 'with', 'joy.'],
    },
    {
      english: 'Her sibling lives in a different city now.',
      vietnamese: 'Anh chị em của cô ấy hiện sống ở một thành phố khác.',
      words: ['Her', 'sibling', 'lives', 'in', 'a', 'different', 'city', 'now.'],
    },
    {
      english: 'They celebrated fifty years of happy marriage last week.',
      vietnamese: 'Họ kỷ niệm năm mươi năm hôn nhân hạnh phúc tuần trước.',
      words: ['They', 'celebrated', 'fifty', 'years', 'of', 'happy', 'marriage', 'last', 'week.'],
    },
    {
      english: 'Our cultural heritage is passed down through generations.',
      vietnamese: 'Di sản văn hóa của chúng tôi được truyền qua các thế hệ.',
      words: ['Our', 'cultural', 'heritage', 'is', 'passed', 'down', 'through', 'generations.'],
    },
    {
      english: 'Every relative joined the household for the holiday tradition.',
      vietnamese: 'Mọi người thân đều về nhà cho truyền thống ngày lễ.',
      words: ['Every', 'relative', 'joined', 'the', 'household', 'for', 'the', 'holiday', 'tradition.'],
    },
  ],

  technology: [
    {
      english: 'The software update fixed many bugs in the system.',
      vietnamese: 'Bản cập nhật phần mềm đã sửa nhiều lỗi trong hệ thống.',
      words: ['The', 'software', 'update', 'fixed', 'many', 'bugs', 'in', 'the', 'system.'],
    },
    {
      english: 'Strong cybersecurity protects our database from attacks.',
      vietnamese: 'An ninh mạng mạnh mẽ bảo vệ cơ sở dữ liệu của chúng tôi khỏi các cuộc tấn công.',
      words: ['Strong', 'cybersecurity', 'protects', 'our', 'database', 'from', 'attacks.'],
    },
    {
      english: 'The algorithm processes data faster than ever before.',
      vietnamese: 'Thuật toán xử lý dữ liệu nhanh hơn bao giờ hết.',
      words: ['The', 'algorithm', 'processes', 'data', 'faster', 'than', 'ever', 'before.'],
    },
    {
      english: 'Innovation in hardware has changed how we use smartphones.',
      vietnamese: 'Đổi mới trong phần cứng đã thay đổi cách chúng ta sử dụng điện thoại thông minh.',
      words: ['Innovation', 'in', 'hardware', 'has', 'changed', 'how', 'we', 'use', 'smartphones.'],
    },
    {
      english: 'Our office network now has much faster bandwidth.',
      vietnamese: 'Mạng văn phòng của chúng tôi hiện có băng thông nhanh hơn nhiều.',
      words: ['Our', 'office', 'network', 'now', 'has', 'much', 'faster', 'bandwidth.'],
    },
    {
      english: 'Artificial intelligence can solve complex problems quickly.',
      vietnamese: 'Trí tuệ nhân tạo có thể giải quyết các vấn đề phức tạp một cách nhanh chóng.',
      words: ['Artificial', 'intelligence', 'can', 'solve', 'complex', 'problems', 'quickly.'],
    },
  ],

  toeic: [
    {
      english: 'The company needs to negotiate a new trade agreement.',
      vietnamese: 'Công ty cần đàm phán một hiệp định thương mại mới.',
      words: ['The', 'company', 'needs', 'to', 'negotiate', 'a', 'new', 'trade', 'agreement.'],
    },
    {
      english: 'Quarterly revenue exceeded the forecast by ten percent.',
      vietnamese: 'Doanh thu quý vượt dự báo mười phần trăm.',
      words: ['Quarterly', 'revenue', 'exceeded', 'the', 'forecast', 'by', 'ten', 'percent.'],
    },
    {
      english: 'The consultant reviewed all business correspondence carefully.',
      vietnamese: 'Chuyên gia tư vấn đã xem xét kỹ lưỡng tất cả thư từ kinh doanh.',
      words: ['The', 'consultant', 'reviewed', 'all', 'business', 'correspondence', 'carefully.'],
    },
    {
      english: 'Headquarters approved the budget to reduce expenditure.',
      vietnamese: 'Trụ sở chính đã phê duyệt ngân sách để giảm chi tiêu.',
      words: ['Headquarters', 'approved', 'the', 'budget', 'to', 'reduce', 'expenditure.'],
    },
    {
      english: 'The subsidiary manages its own merchandise inventory.',
      vietnamese: 'Công ty con tự quản lý hàng tồn kho hàng hóa của mình.',
      words: ['The', 'subsidiary', 'manages', 'its', 'own', 'merchandise', 'inventory.'],
    },
    {
      english: 'Stock prices fluctuate based on market conditions daily.',
      vietnamese: 'Giá cổ phiếu dao động hàng ngày dựa trên điều kiện thị trường.',
      words: ['Stock', 'prices', 'fluctuate', 'based', 'on', 'market', 'conditions', 'daily.'],
    },
  ],
};
